cfg_dict:
task: 
    name: HumanoidAMPSRLTest
    physics_engine: physx
    env: 
        numEnvs: 4096
        envSpacing: 5
        episodeLength: 300
        cameraFollow: True
        enableDebugVis: False
        pdControl: True
        powerScale: 1.0
        controlFrequencyInv: 2
        stateInit: Random
        hybridInitProb: 0.5
        numAMPObsSteps: 2
        localRootObs: False
        contactBodies: ['right_foot', 'left_foot', 'right_shin', 'left_shin']
        terminationHeight: 0.5
        enableEarlyTermination: True
        motion_file: amp_humanoid_walk.npy
        srl_endpos_obs: False
        asset: 
            assetFileName: mjcf/humanoid_srl/humanoid_pretrain.xml
        plane: 
            staticFriction: 1.0
            dynamicFriction: 1.0
            restitution: 0.0
        torque_threshold: 50
        upper_reward_w: 1
        target_v_task: False
        autogen_model: True
    sim: 
        dt: 0.0166
        substeps: 2
        up_axis: z
        use_gpu_pipeline: True
        gravity: [0.0, 0.0, -9.81]
        physx: 
            num_threads: 4
            solver_type: 1
            use_gpu: True
            num_position_iterations: 4
            num_velocity_iterations: 0
            contact_offset: 0.02
            rest_offset: 0.0
            bounce_threshold_velocity: 0.2
            max_depenetration_velocity: 10.0
            default_buffer_size_multiplier: 5.0
            max_gpu_contact_pairs: 8388608
            num_subscenes: 4
            contact_collection: 2
    task: 
        randomize: False
        randomization_params: 
            frequency: 600
            observations: 
                range: [0, 0.002]
                operation: additive
                distribution: gaussian
            actions: 
                range: [0.0, 0.02]
                operation: additive
                distribution: gaussian
            sim_params: 
                gravity: 
                    range: [0, 0.4]
                    operation: additive
                    distribution: gaussian
                    schedule: linear
                    schedule_steps: 3000
            actor_params: 
                humanoid: 
                    color: True
                    rigid_body_properties: 
                        mass: 
                            range: [0.5, 1.5]
                            operation: scaling
                            distribution: uniform
                            setup_only: True
                            schedule: linear
                            schedule_steps: 3000
                    rigid_shape_properties: 
                        friction: 
                            num_buckets: 500
                            range: [0.7, 1.3]
                            operation: scaling
                            distribution: uniform
                            schedule: linear
                            schedule_steps: 3000
                        restitution: 
                            range: [0.0, 0.7]
                            operation: scaling
                            distribution: uniform
                            schedule: linear
                            schedule_steps: 3000
                    dof_properties: 
                        damping: 
                            range: [0.5, 1.5]
                            operation: scaling
                            distribution: uniform
                            schedule: linear
                            schedule_steps: 3000
                        stiffness: 
                            range: [0.5, 1.5]
                            operation: scaling
                            distribution: uniform
                            schedule: linear
                            schedule_steps: 3000
                        lower: 
                            range: [0, 0.01]
                            operation: additive
                            distribution: gaussian
                            schedule: linear
                            schedule_steps: 3000
                        upper: 
                            range: [0, 0.01]
                            operation: additive
                            distribution: gaussian
                            schedule: linear
                            schedule_steps: 3000
train: 
    params: 
        seed: 42
        algo: 
            name: srl_continuous
        model: 
            name: continuous_srl
        network: 
            name: srl
            separate: True
            space: 
                continuous: 
                    mu_activation: None
                    sigma_activation: None
                    mu_init: 
                        name: default
                    sigma_init: 
                        name: const_initializer
                        val: -2.9
                    fixed_sigma: True
                    learn_sigma: False
            mlp: 
                units: [512, 256]
                activation: relu
                d2rl: False
                initializer: 
                    name: default
                regularizer: 
                    name: None
            disc: 
                units: [1024, 512]
                activation: relu
                initializer: 
                    name: default
        load_checkpoint: False
        load_path: 
        config: 
            name: SRLGym_TEST_TITAN
            full_experiment_name: SRLGym_TEST_TITAN
            env_name: rlgpu
            ppo: True
            multi_gpu: False
            mixed_precision: False
            normalize_input: True
            normalize_value: True
            value_bootstrap: True
            num_actors: 4096
            reward_shaper: 
                scale_value: 1
            normalize_advantage: True
            gamma: 0.99
            tau: 0.95
            learning_rate: 3e-05
            lr_schedule: constant
            kl_threshold: 0.008
            score_to_win: 20000
            max_epochs: 20
            save_best_after: 100
            save_frequency: 1000
            print_stats: True
            grad_norm: 1.0
            entropy_coef: 0.0
            truncate_grads: False
            e_clip: 0.2
            horizon_length: 16
            minibatch_size: 32768
            mini_epochs: 6
            critic_coef: 5
            clip_value: False
            seq_len: 4
            bounds_loss_coef: 10
            amp_obs_demo_buffer_size: 200000
            amp_replay_buffer_size: 1000000
            amp_replay_keep_prob: 0.01
            amp_batch_size: 512
            amp_minibatch_size: 4096
            disc_coef: 5
            disc_logit_reg: 0.05
            disc_grad_penalty: 5
            disc_reward_scale: 2
            disc_weight_decay: 0.0001
            normalize_amp_input: True
            task_reward_w: 1.0
            disc_reward_w: 1.0
            actions_num_humanoid: 28
            actions_num_srl: 8
            train_srl_only: False
            humanoid_checkpoint: None
            mirror_loss: True
            sym_loss_coef: 1
            humanoid_obs_masked: False
            start_frame: 0
pbt: 
    enabled: False
task_name: HumanoidAMPSRLTest
experiment: SRLGym_TEST_TITAN
num_envs: 
seed: 42
torch_deterministic: False
max_iterations: 20
physics_engine: physx
pipeline: gpu
sim_device: cuda:0
rl_device: cuda:0
graphics_device_id: 0
num_threads: 4
solver_type: 1
num_subscenes: 4
test: False
checkpoint: 
sigma: 
multi_gpu: False
wandb_activate: True
wandb_group: 
wandb_name: SRLGym_TEST_TITAN
wandb_entity: 
wandb_project: isaacgymenvs
wandb_tags: []
wandb_logcode_dir: 
capture_video: False
capture_video_freq: 1464
capture_video_len: 100
force_render: True
headless: True